### ISSUE TITLE
findmetdata - fix merging of timewindows with same start time

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky#106]
## TODO
 - [x] work in 4.0-release branch
 - [x] fix code
 - [x] add unit test
 - [x] publish 4.0.8
 - [x] cherry-pick commits into master

## behavior

e.g. given
```
  [
    {'start': datetime.datetime(2018, 11, 9, 4, 0), 'end': datetime.datetime(2018, 11, 9, 5, 0)},
    {'start': datetime.datetime(2018, 11, 8, 8, 0), 'end': datetime.datetime(2018, 11, 9, 8, 0)}
  ]
```
what's expected is
```
 [
      {'start': datetime.datetime(2018, 11, 8, 8, 0), 'end': datetime.datetime(2018, 11, 9, 8, 0)}
  ]
```
but what you get is
```
[
   { 'start': datetime.datetime(2018, 11, 8, 8, 0), 'end': datetime.datetime(2018, 11, 9, 5, 0)}
]
```
