### ISSUE TITLE
add support for hysplit trajectories

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky#152]
run hysplit dispersion and/or trajectory in one run one set of traj per fire

***note*** that hysplit trajectories supports multiple fires as long as they start (start hours) at same time

## input & config

**input**
 - fire data:  lat, lng

**config**
 - start (e.g. `'2020-0-23T00:00:00Z'`)
 - start hours (e.g. `[1, 6, 12, 18]`)
 - heights (in meters; e.g. `[100, 100, 5000]`)
 - hysplit binary (or is there only one option?)
 - anything else? 

## TODO
 - [x] decide how much dispersion hysplit code is reusable and move to bluesky.hysplit.*
 - [x] add 'trajectories' module
 - [x] add 'trajectories' target to visualization module
 - [x] write unit tests
 - [x] test hysplit and vsmoke dispersion to make sure dind't break anything
 - [x] test trajectories on small and large data sets

## Need to Decide:
 - run as a separate module `trajectories`, that could be run before or after hysplit **vs.** as an an optional output of hysplit dispersion; if the latter, maybe have a config option like 'modes', which is an array of one or both of 'disperion' and 'trajectories' ***<- decided on separate module***
 - update KML module when 'target' is 'dispersion' to search for and include trajectories **vs** new 'target' of 'trajectories' in  the KML module **vs** new visualization module ***<-- I propose a) new 'trajectories' target and b) updating visualization module to support multiple target;  also maybe a third target 'dispersion+trajectories' to put dispersion and traj in one kml?***
