### ISSUE TITLE
bug: duplicate trajectories

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky#188]
## todo:
 - [x] Only compute trajectories for location if traj start time is within location's time window
 - [x] Group trajectory lines by lat,lng in json output data
 - [x] update unit tests
 - [x] ad hoc test (including viewing output KMZ in google earth)

---

Provided by user:

[duplicate_trajectories.json.txt](https://github.com/pnwairfire/bluesky/files/5268550/duplicate_trajectories.json.txt)
