### ISSUE TITLE
new emissions model - frp-emissions

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky#68]
### BSP todos

- [x] refactor existing models
- [x] add unit tests
- [x] while code is in branch, run example through each model (FEPS, Urbanski, CONSUME) in branch and in master, and make sure results match
- [ ] add frp
- [ ] merge barnch
- [ ] publish new version of bsp
- [ ] upgrade bsp in daily runs project
- [ ] add new daily run using frp, or update current GOES-16 run to use frp
- [ ] test running FRP through ingestion, emissions, findmetdata, plumerising (sev), dispersion, visualization
- [ ] add frp unit tests

### FRP emissions TODOs

- [ ] script to import CE csv into better look-up format (binary or json object)
- [ ] code to look up CE from CSV
- [ ] code to compute heat
- [ ] code to compute PM2.5
- [ ] code to estimate consumption from PM2.5 EFs
- [ ] code to compute other emissions species from estimated consumption

----

  - when used, would replace fuelbeds+consumption+emissions
  - would compute heat and PM2.5 from FRP values

## TODO:
 - implement new model in 
 - try running GOES-16 data through this new calculation scheme

### my questions (to Susan over slack):

 - Sean wrote `Q = FRE / 0.4`, I assume `FRE` is a typo and that he meant `FRP`. Do you think this is true?   ***<— FRE (in joules) = FRP * 300 seconds (i.e. 5 minutes)***
 - Once I compute `Q`, how do I break it out into flaming, smoldering, and residual, or should I not worry about that?  (Btw, I don’t see anything besides vsmoke use heat down stream of emissions.  The FEPS plumerise code that I ported from BSF doesn’t use it as an input.)  ***<— no, just set total to that***
 - To compute PM2.5, Sean mentions using FEER TPM in the equation `PM2.5 = TPM * 0.8`.   How do I get FEER TMP?  My understanding was that we were going to take GOES-16 data and feed it directly into the pipeline, which we’d then use to run FRP emissions followed by plumerise and dispersion. ***<— look at https://github.com/raffscallion/goesfire/blob/master/R/process.R, it multiplies location specific coefficient (Ce_850 in csv from susan) that’s multiplied by FRE to get total particulate mater, which is multiple by 0.8 (80% total PM is PM2.5 ***
 - how to break up PM2.5 into flaming, smoldering, and residual (hysplit emits differently)?  ***<— See what consume does (Susan O. will talk to Susan P.)***
 

### other notes:

 - we’ll need other species too
  - we can divide PM2.5. value by an emissions factor to get mass consumed, then multiple that by other EF’s to get other species.
  - we get get granularity of our current emissions output
    - we can do it based on combustion phase
    - to do it based on fuel category

 - maybe write as a separate package?????….prob not necessary for now

 
## Email from sean

[email](https://mail.google.com/mail/u/0/?zx=2w5tqhjp0gxc#inbox/FMfcgxvwzvMhGMhjPLswvSgVZdHPNPDq)

AirFire,

This is a bit of a summary report as email, so sorry if it’s longer than normal.

#### Relating FRP to Heat

As I relearned through my old textbooks, heat transfer from a fire can be in the form of convection, conduction, or radiation. The landscape is not very conductive, so most of the energy is transferred as convection or radiation. As the name suggests, FRP is measure of radiation only. To convert to total heat, as would be required by FEPS, you need to assume a radiant fraction (χrad). The literature was hard to pin down for this, but the most relevant source I could find was from experimental fires by Morandini et al. (https://doi.org/10.1016/j.ijthermalsci.2013.03.011). They report χrad of 17.4 – 22.4%. Another source (http://iki.cosmos.ru/earth/ppt2005/sukhinin.pdf, about 1/3 down) uses 40%. I suggest we use the more conservative 40% value to get heat for BlueSky:

Q = FRE / 0.4

If we aggregate the GOES data to hourly, we can provide hourly heat as expected by BlueSky. Incidentally, this is a bit roundabout, as I believe the FEPS equations then take this total heat and estimate the convective/conductive parts for plume rise. A better approach for later on would be to use a plume rise scheme designed with FRP in mind, such as the SEV equations. Can anyone point me to the SEV BlueSky code? I’d like to recall what it’s doing.

 #### Relating TPM to PM2.5

The FEER map only contains a single emission factor relating total energy to total particulate matter. To estimate PM2.5, I looked at IMPROVE data. The Sawtooth Wilderness site in Idaho is dominated by smoke, with basically pristine air whenever there isn’t a fire. We measure both PM10 and PM2.5 in IMPROVE, so I looked at the PM2.5/PM10 ratio when PM2.5 was over 30 ug/m3 at the site (i.e., when there was smoke). The ratio is quite consistent, with a median of 0.85 and a tight distribution between 0.8 and 0.9. Thus, most of the mass is PM2.5. If we assume that PM10/TPM is nearly 1, which I think is safe, then we can get PM2.5 emissions from the FEER TPM as:

 

PM2.5 = TPM * 0.8

----

## Attachments

![https://trello-attachments.s3.amazonaws.com/557b6d216ba5a68657fb5344/5b48d84910a632c9d32220b1/9aa63bef6c109846fdbab705142e56c8/FEERv1.0_Ce.csv](https://trello-attachments.s3.amazonaws.com/557b6d216ba5a68657fb5344/5b48d84910a632c9d32220b1/9aa63bef6c109846fdbab705142e56c8/FEERv1.0_Ce.csv)

***(Programatically migrated from Trello)***
